name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запуск пайплайна при пуше в ветку main.

jobs:
  # 1. Тестирование проекта
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9


    - name: Run unittests
      run: python -m unittest discover

  # 2. Сборка Docker-образа
  build:
    runs-on: ubuntu-latest
    needs: test  # Зависит от завершения job "test"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -f project/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest

  # 3. Развертывание на сервере
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Зависит от завершения job "build"
    steps:
    - name: Deploy Docker container on server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Останавливаем и удаляем контейнер, если он не работает
          sudo docker ps -q -f "name=calculator-app" | grep -q . && sudo docker stop calculator-app && sudo docker rm calculator-app

          # Подтягиваем последнюю версию образа с Docker Hub
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
          
          # Устанавливаем X11 сервер внутри контейнера
          sudo docker exec calculator-app bash -c "export DISPLAY=:0 && python3 /app/project/main.py"
          
          # Стартуем контейнер
          sudo docker run -d -p 5000:5000 --name calculator-app ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
        
          
  
