name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запуск пайплайна при пуше в ветку main.

jobs:
  # 1. Тестирование проекта
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10


    - name: Run unittests
      run: python -m unittest discover

  # 2. Сборка Docker-образа
  build:
    runs-on: ubuntu-latest
    needs: test  # Зависит от завершения job "test"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/calculator-app .
        docker push your-dockerhub-username/calculator-app

  # 3. Развертывание на сервере
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Зависит от завершения job "build"
    steps:
    - name: Deploy Docker container on server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker ps -q -f "name=calculator-app" | grep -q . && docker stop calculator-app && docker rm calculator-app
          docker pull your-dockerhub-username/calculator-app
          docker run -d -p 5000:5000 --name calculator-app your-dockerhub-username/calculator-app
