name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запуск пайплайна при пуше в ветку main.

jobs:
  # 1. Тестирование проекта
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      # Устанавливает последнюю версию Python 3.9 для выполнения тестов

    - name: Run unittests
      run: python -m unittest discover
      # Запускает все юнит-тесты в директории проекта

  # 2. Сборка Docker-образа sdca
  build:
    runs-on: ubuntu-latest
    needs: test  # Зависит от завершения job "test"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      # Настройка Docker Buildx для сборки образов

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # Авторизация пользователя в Docker Hub

    - name: Build and push Docker image
      run: |
        docker build -f project/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
      # Сборка Docker образа и его пуш в Docker Hub

    - name: Upload deb package
      uses: actions/upload-artifact@v3
      with:
        name: calculator-deb
        path: ./calculator.deb

  # 3. Развертывание на сервере
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Зависит от завершения job "build"
    steps:
    - name: Deploy Docker container on server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          # Останавливаем и удаляем контейнер, если он не работает
          #sudo docker ps -q -f "name=calculator-app" | grep -q . && sudo docker stop calculator-app && sudo docker rm calculator-app
          
          # Проверяем, существует ли контейнер с именем calculator-app
          if [ -n "$(sudo docker ps -q -f 'name=calculator-app')" ]; then
            sudo docker stop calculator-app
            sudo docker rm calculator-app
          fi
          
          # Подтягиваем последнюю версию образа с Docker Hub
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
          
          sudo docker run -d -p 5000:5000 --name calculator-app ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
      # Развертывание Docker-контейнера на удаленном сервере

#          # Стартуем контейнер с настройками X11
#          sudo docker run --rm -d \
#              -e DISPLAY=$DISPLAY \
#              -v /tmp/.X11-unix:/tmp/.X11-unix \
#              -p 5000:5000 \
#              --name calculator-app \
#              ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest

          
        
          
  
